name: meme_generator
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: 3.2.3 # Dart SDK version
  flutter: 3.16.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  cupertino_icons: ^1.0.2
  riverpod_annotation: ^2.3.4
  image_picker: ^1.0.7
  widgets_to_image: ^0.0.2
  path_provider: ^2.0.1
  gallery_saver: ^2.3.2
  screenshot: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8

  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - images/
